server:
  port: 8080

spring:
  application:
    name: testApp
  datasource:
    url: jdbc:mysql://localhost:3306/bookapp
    username: springuser
    password: springuser
  jpa:
    hibernate:
      ddl-auto: create-drop

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

